name: coin_pay
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  flutter_riverpod: ^2.6.1
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/flags/
    

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        
  
  
  